### ISSUE TITLE
ValueError: Model provided by the configuration not supported

### ISSUE THREAD

**Issue by david-strejc** [VinciGit00/Scrapegraph-ai#259]
Traceback (most recent call last):
  File "/home/david/Work/Programming/searchgraphai/first_try.py", line 18, in <module>
    search_graph = SearchGraph(
  File "/home/david/.local/lib/python3.10/site-packages/scrapegraphai/graphs/search_graph.py", line 47, in __init__
    super().__init__(prompt, config)
  File "/home/david/.local/lib/python3.10/site-packages/scrapegraphai/graphs/abstract_graph.py", line 54, in __init__
    self.graph = self._create_graph()
  File "/home/david/.local/lib/python3.10/site-packages/scrapegraphai/graphs/search_graph.py", line 61, in _create_graph
    smart_scraper_instance = SmartScraperGraph(
  File "/home/david/.local/lib/python3.10/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 47, in __init__
    super().__init__(prompt, config, source)
  File "/home/david/.local/lib/python3.10/site-packages/scrapegraphai/graphs/abstract_graph.py", line 50, in __init__
    ) if "embeddings" not in config else self._create_embedder(
  File "/home/david/.local/lib/python3.10/site-packages/scrapegraphai/graphs/abstract_graph.py", line 304, in _create_embedder
    raise ValueError(
ValueError: Model provided by the configuration not supported
david @ blackbox:Programming/searchgraphai $ cat first_try.py 
from scrapegraphai.graphs import SearchGraph

```
# Define the configuration for the graph
graph_config = {
    "llm": {
        "model": "groq/llama3-8b-8192",
        "api_key": "",
        "temperature": 0
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": "http://localhost:11434",  # set ollama URL arbitrarily
    },
    "max_results": 5,
}

# Create the SearchGraph instance
search_graph = SearchGraph(
    prompt="List me all the traditional recipes from Chioggia",
    config=graph_config
)

# Run the graph
result = search_graph.run()
print(result)
```

**Comment by VinciGit00** [comment]
thank you, we will fix it as soon as possibile

**Comment by VinciGit00** [comment]
Hi, pls update, we have just done a new release

**Comment by VinciGit00** [comment]
closes with d4d913c

**Comment by ManikSinghSarmaal** [comment]
Can you tellme how to use the updated version I just downloaded the scrapegraphai module with pip and I'm getting a similar error like above-

`Traceback (most recent call last):
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/searchgraph.py", line 25, in <module>
    smart_scraper_graph = SearchGraph(
                          ^^^^^^^^^^^^
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/search_graph.py", line 43, in __init__
    super().__init__(prompt, config)
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/abstract_graph.py", line 54, in __init__
    self.graph = self._create_graph()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/search_graph.py", line 57, in _create_graph
    smart_scraper_instance = SmartScraperGraph(
                             ^^^^^^^^^^^^^^^^^^
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 47, in __init__
    super().__init__(prompt, config, source)
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/abstract_graph.py", line 50, in __init__
    ) if "embeddings" not in config else self._create_embedder(
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/abstract_graph.py", line 287, in _create_embedder
    raise ValueError(
ValueError: Model provided by the configuration not supported`

**Comment by PeriniM** [comment]
Hei @ManikSinghSarmaal can you copy paste your code?

**Comment by ManikSinghSarmaal** [comment]
> Hei @ManikSinghSarmaal can you copy paste your code?

Hi my code for the above error is -
`from scrapegraphai.graphs import SearchGraph
import nest_asyncio  
nest_asyncio.apply()  
# Configuration dictionary for the graph
graph_config = {
    "llm": {
        "model": "ollama/llama3",  
        "temperature": 0, 
        "format": "json",  
        "base_url": "http://localhost:11434",  
    },
        "embeddings": {
        "model": "ollama/nomic-embed-text",  
        "base_url": "http://localhost:11434",  # Set the base URL for Ollama
    },
    "verbose": True,  # Enable verbose mode for debugging purposes
    "max_results": 5,
    'headless':False,
}


# Initialize SmartScraperGraph with prompt, source, and configuration
smart_scraper_graph = SearchGraph(
    #prompt="List all the content", 
    prompt="Latest Tech News",
    config=graph_config 
)

result = smart_scraper_graph.run()

print(result)

# Prettify the result and display the JSON
import json

output = json.dumps(result, indent=2) 

line_list = output.split("\n")  # Split the JSON string into lines

for line in line_list:
    print(line)`
    
    
Error I'm encountering is - 
`Traceback (most recent call last):
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/Search.py", line 23, in <module>
    smart_scraper_graph = SearchGraph(
                          ^^^^^^^^^^^^
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/search_graph.py", line 43, in __init__
    super().__init__(prompt, config)
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/abstract_graph.py", line 54, in __init__
    self.graph = self._create_graph()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/search_graph.py", line 57, in _create_graph
    smart_scraper_instance = SmartScraperGraph(
                             ^^^^^^^^^^^^^^^^^^
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 47, in __init__
    super().__init__(prompt, config, source)
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/abstract_graph.py", line 50, in __init__
    ) if "embeddings" not in config else self._create_embedder(
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maniksinghsarmaal/Downloads/scrapegraphai/ScrapegraphAIOllamallama3/scrapegraphAI/lib/python3.11/site-packages/scrapegraphai/graphs/abstract_graph.py", line 287, in _create_embedder
    raise ValueError(
ValueError: Model provided by the configuration not supported`

**Comment by ManikSinghSarmaal** [comment]
> Hei @ManikSinghSarmaal can you copy paste your code?

Hi the code for the above ValueError: Model provided by the configuration not supported is-
```python
from scrapegraphai.graphs import SearchGraph
import nest_asyncio  
nest_asyncio.apply()  
# Configuration dictionary for the graph
graph_config = {
    "llm": {
        "model": "ollama/llama3",  
        "temperature": 0, 
        "format": "json",  
        "base_url": "http://localhost:11434",  
    },
        "embeddings": {
        "model": "ollama/nomic-embed-text",  
        "base_url": "http://localhost:11434",  # Set the base URL for Ollama
    },
    "verbose": True,  # Enable verbose mode for debugging purposes
    "max_results": 5,
    'headless':False,
}


smart_scraper_graph = SearchGraph(
    #prompt="List all the content", 
    prompt="Latest Tech News",
    config=graph_config 
)

result = smart_scraper_graph.run()

print(result)

# Prettify the result and display the JSON
import json

output = json.dumps(result, indent=2) 

line_list = output.split("\n") 

for line in line_list:
    print(line)
```

**Comment by liaoliaojun** [comment]
Is there any further progress on this issue?
