### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by jasontsoi7885** [VinciGit00/Scrapegraph-ai#288]
**Describe the bug**
Collecting yahoo-search-py==0.3 (from scrapegraphai)
  Using cached yahoo-search-py-0.3.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/Jason/anaconda3/envs/webscrapeAI/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/Jason/anaconda3/envs/webscrapeAI/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/Jason/anaconda3/envs/webscrapeAI/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Users/Jason/anaconda3/envs/webscrapeAI/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/Jason/anaconda3/envs/webscrapeAI/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/l6/h62x6xvj0dq14d12q12yt2cm0000gn/T/pip-build-env-49k8dv55/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/l6/h62x6xvj0dq14d12q12yt2cm0000gn/T/pip-build-env-49k8dv55/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/l6/h62x6xvj0dq14d12q12yt2cm0000gn/T/pip-build-env-49k8dv55/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**To Reproduce**
1. When I install the [Scrapegraph-ai] using a new env, I got the error of install yahoo-search-py

**Desktop (please complete the following information):**
 - Device: Macbook M2 Pro 16GB
 - OS: 14.3.1 (23D60) 
 - Env: Anaconda (Python 3.12.3)

**Comment by PeriniM** [comment]
Hey @jasontsoi7885 can you try installing it again in an enviroment with python version less than 3.12, like 3.11?

**Comment by jasontsoi7885** [comment]
@PeriniM I successfully install the package, but when I try to run the demo code:
`from scrapegraphai.graphs import SmartScraperGraph

graph_config = {
    "llm": {
        "model": "ollama/mistral",
        "temperature": 0,
        "format": "json",  # Ollama needs the format to be specified explicitly
        "base_url": "http://localhost:11434",  # set Ollama URL
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": "http://localhost:11434",  # set Ollama URL
    },
    "verbose": True,
}

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the projects with their descriptions",
    # also accepts a string with the already downloaded HTML code
    source="https://perinim.github.io/projects",
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)
`

I got a error: [/Users/Jason/anaconda3/envs/webscrapeAI311/lib/python3.11/site-packages/tqdm/auto.py:21](https://file+.vscode-resource.vscode-cdn.net/Users/Jason/anaconda3/envs/webscrapeAI311/lib/python3.11/site-packages/tqdm/auto.py:21): TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
--- Executing Fetch Node ---

**Comment by Kingki19** [comment]
> I got a error: [/Users/Jason/anaconda3/envs/webscrapeAI311/lib/python3.11/site-packages/tqdm/auto.py:21](https://file+.vscode-resource.vscode-cdn.net/Users/Jason/anaconda3/envs/webscrapeAI311/lib/python3.11/site-packages/tqdm/auto.py:21): TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
from .autonotebook import tqdm as notebook_tqdm
--- Executing Fetch Node ---

It's seems that you don't upgrade your Jupyter and ipywidgets in local machine.

**Comment by VinciGit00** [comment]
yes, please upgrade Jupyter and ipywidgets
