### ISSUE TITLE
ImportError: cannot import name 'validate_core_schema' from 'pydantic_core'  

### ISSUE THREAD

**Issue by vc815** [VinciGit00/Scrapegraph-ai#331]
Hello,

I've encountered an import error while working with `pydantic_core` and I'm unsure how to resolve it. The error message is as follows:

I've tried updating the package and checking for any typos in the import statement, but the issue persists. Could someone guide me on how to fix this error? Any help would be greatly appreciated!

Additional Information: I installed it in a conda environment on a Windows 11 system.

Thank you!

**Comment by PeriniM** [comment]
Hey @vc815 can you send the error?

**Comment by vc815** [comment]
Traceback (most recent call last):
  File "D:\test\Scrapegraph-ai-main\t.py", line 1, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\scrapegraphai\graphs\__init__.py", line 5, in <module>
    from .abstract_graph import AbstractGraph
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\scrapegraphai\graphs\abstract_graph.py", line 9, in <module>
    from langchain_aws import BedrockEmbeddings
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\langchain_aws\__init__.py", line 1, in <module>
    from langchain_aws.chat_models import BedrockChat, ChatBedrock
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\langchain_aws\chat_models\__init__.py", line 1, in <module>
    from langchain_aws.chat_models.bedrock import BedrockChat, ChatBedrock
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\langchain_aws\chat_models\bedrock.py", line 35, in <module>
    from langchain_core.tools import BaseTool
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\langchain_core\tools.py", line 45, in <module>
    from langchain_core.prompts import (
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\langchain_core\prompts\__init__.py", line 27, in <module>
    from langchain_core.prompts.base import (
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\langchain_core\prompts\base.py", line 22, in <module>
    from langchain_core.output_parsers.base import BaseOutputParser
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\langchain_core\output_parsers\__init__.py", line 20, in <module>
    from langchain_core.output_parsers.json import JsonOutputParser, SimpleJsonOutputParser
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\langchain_core\output_parsers\json.py", line 28, in <module>
    PydanticBaseModel = Union[BaseModel, pydantic.BaseModel]  # type: ignore
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\pydantic\__init__.py", line 395, in __getattr__
    module = import_module(module_name, package=package)
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\pydantic\main.py", line 17, in <module>
    from ._internal import (
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\pydantic\_internal\_decorators.py", line 15, in <module>
    from ._core_utils import get_type_ref
  File "D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\pydantic\_internal\_core_utils.py", line 14, in <module>
    from pydantic_core import validate_core_schema as _validate_core_schema
ImportError: cannot import name 'validate_core_schema' from 'pydantic_core' (D:\ProgramData\Anaconda3\envs\scrap\lib\site-packages\pydantic_core\__init__.py)

**Comment by PeriniM** [comment]
Hey @vc815 the new version should have this fixed!
Cheers
